version: '3'

# volumes:
#     mariadb_vol:
#     wordpress_vol:

services:
        mariadb:
            image: mariadb:local
            build:
              context: requirements/mariadb
              args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWD: ${DB_PASSWD}
                DB_RPASSWD: ${DB_RPASSWD}
            container_name: mariadb
            volumes:
                - /home/ahkecha/data/mariadb:/database/mysql
            restart: always
            networks:
              - inception
        wordpress:
            image: wordpress:local
            build: requirements/wordpress
            container_name: wp
            volumes:
              - /home/ahkecha/data/wordpress:/var/www/html
            environment:
                WP_ADMIN: ${WP_ADMIN}
                WP_ADMINPASSWORD: ${WP_ADMINPASSWORD}
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWD: ${DB_PASSWD}
                WP_ADMINMAIL: ${WP_ADMINMAIL}
                EDITOR_USER: ${EDITOR_USR}
                EDITOR_PASSWD: ${EDITOR_PASSWD}
                EDITOR_MAIL: ${EDITOR_MAIL}
            depends_on:
              - mariadb
            restart: always
            networks:
              - inception
        nginx:
            image: nginx:local
            build: ./requirements/nginx/
            container_name: nginx
            volumes:
                - /home/ahkecha/data/wordpress:/var/www/html
                - /home/ahkecha/data/nginx:/var/logs/nginx
                - /home/ahkecha/data/adminer:/var/www/data
                - /home/ahkecha/data/hugo:/var/www/hugo
            ports:
                - "443:443"
            networks:
                - inception
            restart: always
            depends_on:
                - wordpress
                - mariadb
                - adminer
                - hugo
        vsftpd:
          image: vsftpd:local
          build: requirements/bonus/VsFTPd
          container_name: vsftpd
          volumes:
            - /home/ahkecha/data/wordpress:/www/wordpress/
          ports:
            - "20:20"
            - "21:21"
            - "10090-10100:10090-10100"
          depends_on:
            - wordpress
          environment:
              FTP_USR: ${FTP_USR}
              FTP_PASSWD: ${FTP_PASSWD}
          networks:
            - inception
        redis:
          image: redis:local
          build: ./requirements/bonus/redis
          container_name: redis
          depends_on:
            - wordpress
          restart: always
          networks:
            - inception
        adminer:
          image: adminer:local
          build: ./requirements/bonus/adminer
          container_name: adminer
          volumes:
            - /home/ahkecha/data/adminer:/var/www/adminer
          depends_on:
            - mariadb
          restart: always
          networks:
            - inception
        hugo:
          image: hugo:local
          build: ./requirements/bonus/hugo
          container_name: hugo
          volumes:
            - /home/ahkecha/data/hugo:/static
          restart: always
          networks:
            - inception
        cadvisor:
          image: cadvisor:local
          build: ./requirements/bonus/cadvisor
          container_name: cadvisor
          restart: always
          privileged: true
          devices:
            - /dev/kmsg
          volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
          networks:
            - inception
networks:
    inception:
        driver: bridge
