version: '3'
services:
        mariadb:
            image: mariadb:local
            build:
              context: srcs/mariadb
              args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWD: ${DB_PASSWD}
                DB_RPASSWD: ${DB_RPASSWD}
            container_name: mariadb
            volumes:
                - ./data/mysql:/database/mysql
            ports:
                - "3306:3306"
            # env_file:
            #   - .env
            restart: always
            networks:
              - wordpress
        wordpress:
            image: wordpress:local
            build:
              context: srcs/wordpress
              args:
                WP_ADMIN: ${WP_ADMIN}
                WP_ADMINPASSWORD: ${WP_ADMINPASSWORD}
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWD: ${DB_PASSWD}
                WP_ADMINMAIL: ${WP_ADMINMAIL}
                EDITOR_USER: ${EDITOR_USR}
                EDITOR_PASSWD: ${EDITOR_PASSWD}
                EDITOR_MAIL: ${EDITOR_MAIL}
            container_name: wp
            volumes:
              - ./data/wordpress:/var/www/html
            env_file:
              - .env
            depends_on:
              - mariadb
            networks:
              - wordpress
        nginx:
            image: nginx:local
            build: ./srcs/nginx/
            container_name: nginx
            volumes:
                - ./data/wordpress:/var/www/html
                - ./data/nginx:/var/logs/nginx
            ports:
                - "443:443"
            networks:
                - wordpress
            depends_on:
                - wordpress
                - mariadb
        vsftpd:
          image: vsftpd:local
          build: srcs/bonus/VsFTPd
          container_name: vsftpd
          volumes:
            - ./data/wordpress:/www/wordpress/
          ports:
            - "20:20"
            - "21:21"
            - "10090-10100:10090-10100"
          depends_on:
            - wordpress
          env_file:
            - .env
          networks:
            - wordpress
        redis:
          image: redis:local
          build: ./srcs/bonus/redis
          container_name: redis
          ports:
            - "6379:6379"
          depends_on:
            - wordpress
          networks:
            - wordpress
networks:
    wordpress:
        driver: bridge
