version: '3'

volumes:
    mariadb_vol:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: "/tmp/mariadb"
    wordpress_vol:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: "/tmp/wordpress"


services:
        mariadb:
            image: mariadb:local
            build:
              context: srcs/mariadb
              args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWD: ${DB_PASSWD}
                DB_RPASSWD: ${DB_RPASSWD}
            container_name: mariadb
            volumes:
                - mariadb_vol:/database/mysql
            ports:
                - "3306:3306"
            restart: always
            networks:
              - inception
        wordpress:
            image: wordpress:local
            build: srcs/wordpress
            container_name: wp
            volumes:
              - wordpress_vol:/var/www/html
            environment:
                WP_ADMIN: ${WP_ADMIN}
                WP_ADMINPASSWORD: ${WP_ADMINPASSWORD}
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWD: ${DB_PASSWD}
                WP_ADMINMAIL: ${WP_ADMINMAIL}
                EDITOR_USER: ${EDITOR_USR}
                EDITOR_PASSWD: ${EDITOR_PASSWD}
                EDITOR_MAIL: ${EDITOR_MAIL}
            depends_on:
              - mariadb
            restart: always
            networks:
              - inception
        nginx:
            image: nginx:local
            build: ./srcs/nginx/
            container_name: nginx
            volumes:
                - wordpress_vol:/var/www/html
                - ./data/nginx:/var/logs/nginx
                - ./data/adminer:/var/www/data
                - ./data/hugo:/var/www/hugo
            ports:
                - "443:443"
            networks:
                - inception
            restart: always
            depends_on:
                - wordpress
                - mariadb
                - adminer
                - hugo
        vsftpd:
          image: vsftpd:local
          build: srcs/bonus/VsFTPd
          container_name: vsftpd
          volumes:
            - wordpress_vol:/www/wordpress/
          ports:
            - "20:20"
            - "21:21"
            - "10090-10100:10090-10100"
          depends_on:
            - wordpress
          environment:
              FTP_USR: ${FTP_USR}
              FTP_PASSWD: ${FTP_PASSWD}
          networks:
            - inception
        redis:
          image: redis:local
          build: ./srcs/bonus/redis
          container_name: redis
          ports:
            - "6379:6379"
          depends_on:
            - wordpress
          restart: always
          networks:
            - inception
        adminer:
          image: adminer:local
          build: ./srcs/bonus/adminer
          container_name: adminer
          volumes:
            - ./data/adminer:/var/www/adminer
          depends_on:
            - mariadb
          restart: always
          networks:
            - inception
        hugo:
          image: hugo:local
          build: ./srcs/bonus/hugo
          container_name: hugo
          volumes:
            - ./data/hugo:/static
          restart: always
          networks:
            - inception
        snort:
          image: snort:local
          build: ./srcs/bonus/snort
          container_name: snort
          restart: always
          networks:
            - inception
networks:
    inception:
        driver: bridge
